<!DOCTYPE HTML>
<html>
<head>
      <title>Book store</title>
<meta charset="utf-8">
</head>

<body background="book(bg).jpg" style="background-repeat:repeat-y"
leftmargin="50" rightmargin="50">

<table border = "0" align="center" width="90%" 
               cellpadding="15" cellspacing="0">

	 <tr><td>
               <table border="0" align="right" width="100%">
			<tr>

			<td align="center" bgcolor="#cccccc">
			
			<form action ="auto.phtml" method="post"><!--auto.phtml eto fail dla avtorizacii-->

			 <table>
				<tr><td align="right"><font size=-2>LOGIN:</font></td>
				   <td align="left">
				     <input type=text style="width:60; height:20;"name=login></td></tr>

				<tr><td align="right"><font size=-2>PASSW:</font></td>
				  <td align="left">
					<input type=password style="width:60;height:20;name=pass">

						<input type=submit value=ok style="height:20;"></td></tr><!--knopka OK-->
			  </table>
				  
				  <b><small>
					  <?php
					  if (isset($_session["log"]))
					  {
						  print $_session["log"];
						  print "<br> <a href= 'cabinet.phtml'>Personal Area</a>";
					  }
					  ?>
					  </small></b></td>
			</form>
						
			<td colspan="4" align="center" bgcolor="#ccccff">
			   <a href = "index.phtml"><font face="Arial" size="+3"><i><b>BOOK STORE</b></i></a>
					  </font></td></tr>
					  
					  
			<tr><td align="center" bgcolor="#aaddff" width="20%" height = "25">
			<a href="catalog.phtml"><b>CATALOG</b></a></td><!--KATALOG-->

			<td align="center" bgcolor="#ddaaff" width="20%">
			<a href="basket.phtml"><b>BASKET</b></a></td><!--KORZINA-->	

			<td align="center" bgcolor="#aaaaff" width="20%">
			<a href="reg.phtml"><b>REGISTRATION</b></a></td>

			<td align="center" bgcolor="ffaaff" width="20%">
			<a href="order.phtml"><b>ORDER</b></a></td>  <!--ZAKAZ ctranica-->

			<td align="center" bgcolor="#aaffee" width="20%">
			<a href="exit.phtml"><b>EXIT</b></a></td> 
              </tr>
			  </table>
              </td></tr>
			  <tr><td align="center" bgcolor=<?echo $color?>><font face="Arial" size="+2"> 
              <i><?php echo $title?></i></font><br> 
              </td></tr> 
			  