<?php
$title="Welcome!";
$color="#ccccff";
include("header.phtml");
?>
<tr><td bgcolor ="#ffffff">
<center><h2><font color="#555599"><br>Welcome to our
electronic bookstore !!! <br><br>Literature
the most famous publishers. Any reader is compulsory
find a book to your liking! We offer computer literature
encyclopedias reference books most famous works of art
classics and contemporaries and much, much more!</font></h2></center>
</td></tr>
<tr><td bgcolor ="#ffffff">
<center><hr><br>
Welcome to Book Store</center></td></tr>
</table>
</body>
</html>