<!DOCTYPE HTML>
<html>
<head>
      <title>Book store</title>
<meta charset="utf-8">
</head>

<body background="book(bg).jpg" style="background-repeat:repeat-y"
leftmargin="50" rightmargin="50">

<table border = "0" align="center" width="90%" 
               cellpadding="15" cellspacing="0">

	 <tr><td>
               <table border="0" align="right" width="100%">
			<tr>

			<td align="center" bgcolor="#cccccc">
			<form action ="auto.phtml" method="post"><!--auto.phtml eto fail dla avtorizacii-->

			  <table>
			<tr><td align="right"><font size=-2>LOGIN:</font></td>
			<td align="left">
			<input type=text style="width:60; height:20;"name=login></td></tr>

				<tr><td align="right"><font size=-2>PASSW:</font></td>
				  <td align="left">
					<input type=password style="width:60;height:20;name=pass"><br>

			<input type=submit value=ok style="height:20" align ="center"></td></tr><!--knopka OK-->
				  
				  </table>
					  </td>
						</form>
			<td colspan="4" align="center" bgcolor="#ccccff">
			   <font face="Arial" size="+3"><i><b>BOOK STORE</b></i>
					  </font></td>
							  </tr>
			<tr><td align="center" bgcolor="#aaddff" width="20%" height = "25">
			<a href="catalog.phtml"><b>CATALOG</b></a></td><!--KATALOG-->

			<td align="center" bgcolor="#ddaaff" width="20%">
			<a href="basket.phtml"><b>BASKET</b></a></td><!--KORZINA-->	

			<td align="center" bgcolor="#aaaaff" width="20%">
			<a href="reg.phtml"><b>REGISTRATION</b></a></td>

			<td align="center" bgcolor="ffaaff" width="20%">
			<a href="order.phtml"><b>ORDER</b></a></td>  <!--ZAKAZ ctranica-->

			<td align="center" bgcolor="#aaffee" width="20%">
			<a href="exit.phtml"><b>EXID</b></a></td> 

			</tr>
				</table>
     </td></tr>

<tr><i><td align="center" bgcolor="#ccccff">WELCOME to BOOK STORE!!<font face="Arial" size="+2">
      </i></font><br>
	      </td></tr>

		  
<tr bgcolor="white"><td >
<center><h2><font color="#555599"><br>Добро пожаловать в наш 
электронный книжный магазин!!! <br><br>Здесь предоставлена литература 
самых известных российских издательств. Любой читатель обязательно 
найдет себе книгу по вкусу!Мы предлагаем компьютерную литературу 
энциклопедии справочники самые известные художественные произведения 
классиков и современников и многое-многое другое!
</font></h2></center>
</td></tr>

<tr><td bgcolor="white"><center><hr><br>
<a href="Welcome(Home page).phtml">GO to Home Page</a>
</center></td></tr>

</table>
</body>
</html>